# Generated by Django 4.0.3 on 2022-07-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingblog', '0011_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
