# Generated by Django 4.0.3 on 2022-07-06 20:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingblog', '0013_remove_post_content_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
