# Generated by Django 4.0.3 on 2022-07-06 21:32

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kingblog', '0014_postlab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postlab',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
